name: Build RF Bot EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          version: '8.0.x'

      - name: Restore и Publish
        run: |
          cd csharp
          dotnet restore
          dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained -c Release

      - name: Настройка Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd bin\Release\net8.0-windows\win-x64\publish
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          echo "Создаем файл с результатом сборки"
          echo "Build completed at $(date)" > build-info.txt

          git add .
          git commit -m "Build: rf-bot.exe"

          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push -f origin HEAD:builds
