- name: Save EXE to builds branch
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    cd csharp\publish
    git init
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"

    git add .
    git commit -m "Build: rf-bot.exe"

    git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
    git push -f origin HEAD:builds
